// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jukrxqwnrluyfxjszpkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1a3J4cXducmx1eWZ4anN6cGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjUzMTAsImV4cCI6MjA2MDU0MTMxMH0.eE4e7beeaKRfXSjC1yxNg9s-P9_clcSmKhsxtwC3Ysg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
